<h1> Комментарий ревьюера </h1>

Привет, Александр!
Меня зовут Виктория Ильина, и я буду проверять твой проект. Предлагаю общаться на "ты", но если тебе будет не комфортно, обязательно сообщи и мы перейдем на "вы". 

Моя основная цель - не указать на совершённые тобой ошибки, а поделиться своим опытом и помочь тебе стать специалистом по Data Science. Ты уже проделал большую работу над проектом, но давай сделаем его ещё лучше. Ниже ты найдёшь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать различные цвета, чтобы было легче воспринимать мои комментарии:

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Так выделены самые важные замечания. Без их отработки проект не будет принят.
</div>

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Так выделены небольшие замечания. Одно-два таких замечания в проекте допустимы, но если их будет больше - тебе будет необходимо внести исправления. Однако, если перед нами стоит цель не просто сдать проект и забыть, а приобрести новые знания и успешно применять их в будущем, я бы всё-таки рекомендовала тебе прорабатывать эти недочёты.
</div>
    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Так я выделю все остальные комментарии.
</div>
    
Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии - пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Например, вот так.
</div>

Давай посмотрим, что получилось!

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('/datasets/insurance.csv')
print (data)
data.info()

      Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   i

<div class="alert alert-info">
<font color='black'> <b> Имеем 5 столбцов с одинаковым количеством строк и не имеющими пропусков. Столбцы с 0 по 3 - признаки, 4 столбец - целевое значение </font> <b>

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Отсутствуют твои комментарии по поводу данных
      <div class="alert alert-info">
     Комментарий студента:</h2>  Сделал </div>
</div>

    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Хорошо =)
</div>

In [3]:
features = data.drop("Страховые выплаты", axis=1)
target = data["Страховые выплаты"]


In [4]:
A = np.random.rand(4,4)
print (A)
np.linalg.inv(A)

[[0.52587566 0.82931321 0.22396945 0.45374806]
 [0.39749096 0.2936987  0.61995496 0.30860666]
 [0.45326117 0.11831595 0.04991014 0.41904771]
 [0.00789858 0.14687651 0.20359012 0.25803313]]


array([[ 0.06874472,  1.00058505,  1.30901015, -3.44342484],
       [ 1.55825869, -0.48033901, -1.38820856,  0.08876604],
       [-0.55943233,  1.77554595, -0.9140281 ,  0.34459683],
       [-0.44769323, -1.15813148,  1.47129552,  3.65846043]])

In [5]:
model_1 = LinearRegression()
model_1.fit(features, target)
r2 = model_1.score(features, target) 
print (r2)

0.4249455028666801


In [6]:
features_1=features @ A
model_2 = LinearRegression()
model_2.fit(features_1, target)
r2_new = model_2.score(features_1, target) 
print (r2_new)

0.4249455028666864


<div class="alert alert-info">
<font color='black'> <b> Видно, что при умножении признаков на случайную матрицу метрика R2 не изменилась </font> <b>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Верно, таким образом в случае домножения матрицы признаков на случайную обратимую матрицу можно обеспечить защиту данных, не особо потеряв в качестве модели. (Незначительное отличие вызвано особенностью преобразования матриц и чисел с плавающей точкой, это норма)
</div>


## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** R2 не изменится

**Обоснование:** $$
a = X(X^T X)^{-1}X^T y
$$
$$
a1 = X P ((XP)^T X P)^{-1}(X P)^T y= X P (P^T X^TX P)^{-1} (P^T X^T) y = X P P^{-1}(X^TX)^{-1} (P^T)^{-1} (P^T X^T) y= X (X^TX)^{-1}X^T y
$$



<div class="alert alert-info">
<font color='black'> <b> Видим, что a=a1, т.е. при умножении X на случайную матрицу P предсказания не изменятся, следовательно и R2 останется прежней </font> <b>

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> К сожалению, у тебя допущена ошибка в доказательстве, так как для неквадратных матриц $X$ и $X^T$ обратных матриц не существует, то мы не можем раскрывать $(X^T X)^{-1}$
    
Теория по обратным матрицам: https://www.berdov.com/works/matrix/obratnaya-matrica/ 
    <div class="alert alert-info">
     Комментарий студента:</h2>  Поправил, проделал операции с P и сократил P,  т.к. P - обратимая матрица </div>



    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Теперь верно =)
</div>

## Алгоритм преобразования

**Алгоритм**

<div class="alert alert-info">
<font color='black'> <b> Изменим признаки, умножив их на 25 и вычтем 300. После этого умножим на матрицу А </font> <b>

**Обоснование**


## Проверка алгоритма

In [7]:
features_2=(features*25+300) @ A
model_3 = LinearRegression()
model_3.fit(features_2, target)
r2_test = model_3.score(features_2, target) 
print (r2_test)

0.4249455028666568


<div class="alert alert-info">
<font color='black'> <b> Метрика R2 не изменилась. Если делать одинаковые операции с каждым числом матрицы признаков, зависимости между ними не изменятся (получившийся множитель можно попросту сократить), поэтому и R2 останется прежней </font> <b>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Да, верно
</div>

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Спасибо тебе за проделанную работу, к сожалению, сейчас я не могу принять твой проект, поэтому тебе придётся ещё немного поработать:
 
- добавить твои комментарии по поводу данных;
- исправить ошибку в доказательстве.
    
До скорой встречи, если у тебя есть какие-то вопросы или ты хочешь какую-то подборку статей, то обязательно пиши =)
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Дополнительные материалы:

Обзоры по применению криптографии в машинном обучении: https://arxiv.org/pdf/1902.04109.pdf, https://www.researchgate.net/publication/342746786_Some_Applications_of_Machine_Learning_in_Cryptography

Небольшой обзор на Шифр Хилла: https://habr.com/ru/post/595281/
   
Примеры использования линейной алгебры в машинном обучении:
https://machinelearningmastery.com/examples-of-linear-algebra-in-machine-learning/
    
Для чего нужна математика в машинном обучении?
https://proglib.io/p/dlya-chego-nuzhen-matematicheskiy-analiz-v-mashinnom-obuchenii-2021-02-15

Большая статья по векторам:
https://neptune.ai/blog/understanding-vectors-from-a-machine-learning-perspective  

Можно ещё дополнительно посмотреть лекции от МФТИ https://www.youtube.com/playlist?list=PLk4h7dmY2eYHHTyfLyrl7HmP-H3mMAW08
    
Классная серия роликов по линейной алгебре на английском (можно включить автоматические русские субтитры): https://www.youtube.com/playlist?list=PLRDl2inPrWQW1QSWhBU0ki-jq_uElkh2a
    
Удачи в будущих проектах и работе =)
</div>
